# Case Study 2: Data Scope and Reference Datasets: Futures-Based Options Case Study (CME with CBOE Benchmark)

### Load the CSV files

In [4]:
from pathlib import Path
import pandas as pd

# --- Robust base directory resolution ---
try:
    BASE_DIR = Path(__file__).resolve().parent   # .py script
except NameError:
    BASE_DIR = Path.cwd()                        # Jupyter notebook

DATA_DIR = BASE_DIR / "ch03_csv"
assert DATA_DIR.exists(), f"Missing folder: {DATA_DIR}"

print("Using DATA_DIR:", DATA_DIR.resolve())

csv_files = {
    "es_futures_quote": "es_futures_quote.csv",
    "es_futures_specs": "es_futures_specs.csv",
    "es_options_specs": "es_options_specs.csv",
    "es_options_chain": "es_options_chain_synthetic.csv",
    "quikstrike_inputs": "quikstrike_inputs_sample.csv",
    "es_expirations": "es_expirations.csv",
    "es_vol_observations": "es_vol_observations.csv",
    "spx_options_chain": "spx_options_chain_sample.csv",
    "xsp_options_chain": "xsp_options_chain_sample.csv",
    "spx_specs": "spx_specs.csv",
}

dfs = {}
missing = []

for k, fname in csv_files.items():
    path = DATA_DIR / fname
    if path.exists():
        dfs[k] = pd.read_csv(path)
    else:
        missing.append(fname)

if missing:
    print("WARNING: Missing CSV files:")
    for f in missing:
        print("  -", f)

summary = pd.DataFrame(
    [{"dataset": k, "rows": v.shape[0], "cols": v.shape[1]} for k, v in dfs.items()]
)

print(summary)

Using DATA_DIR: C:\Users\mbettaiebcapbonconsu\Documents\B37441_OptionsPricingWithPython_Code\Ch 04\ch04_csv
               dataset  rows  cols
0     es_futures_quote     9     2
1     es_futures_specs     7     2
2     es_options_specs     7     2
3     es_options_chain     1     5
4    quikstrike_inputs     1     4
5       es_expirations     4     3
6  es_vol_observations     4     3
7    spx_options_chain     4     5
8    xsp_options_chain     2     5
9            spx_specs     6     2

### DataFrames

In [5]:
for name, df in dfs.items():
    print("\n" + "=" * 80)
    print(f"DATASET: {name}")
    print(f"Shape: {df.shape}")
    print("Columns:", list(df.columns))
    print("-" * 80)
    display(df.head(10))

================================================================================
DATASET: es_futures_quote
Shape: (9, 2)
Columns: ['Field', 'Value']
--------------------------------------------------------------------------------

              Field                Value
0          Contract  ES (E-mini S&P 500)
1        Trade Date  2025-01-15 00:00:00
2        Last Price              4850.25
3              Open               4830.5
4              High              4872.75
5               Low                 4821
6  Settlement Price                 4848
7            Volume              1450000
8     Open Interest              2750000

================================================================================
DATASET: es_futures_specs
Shape: (7, 2)
Columns: ['Parameter', 'Value']
--------------------------------------------------------------------------------

         Parameter                      Value
0    Contract Size        $50 × S&P 500 Index
1     Minimum Tick          0.25 index points
2       Tick Value                       12.5
3    Trading Hours  Nearly 24 hours (Sun–Fri)
4  Contract Months         Mar, Jun, Sep, Dec
5       Settlement               Cash settled
6         Exchange                        CME

================================================================================
DATASET: es_options_specs
Shape: (7, 2)
Columns: ['Parameter', 'Value']
--------------------------------------------------------------------------------

             Parameter                               Value
0           Underlying              E-mini S&P 500 Futures
1  Contract Multiplier                         $50 × index
2            Tick Size                                0.25
3           Tick Value                                12.5
4       Exercise Style    American & European (by product)
5           Settlement  Cash or Futures (product-specific)
6          Expirations          Weekly, Monthly, Quarterly

================================================================================
DATASET: es_options_chain
Shape: (1, 5)
Columns: ['Expiry', 'Strike', 'Call', 'Put', 'IV']
--------------------------------------------------------------------------------

       Expiry  Strike   Call   Put   IV
0  2025-03-15    4800  176.3  78.9  0.2

================================================================================
DATASET: quikstrike_inputs
Shape: (1, 4)
Columns: ['Date', 'Futures Settlement', 'Call Settle (4800)', 'Put Settle (4800)']
--------------------------------------------------------------------------------

         Date  Futures Settlement  Call Settle (4800)  Put Settle (4800)
0  2025-01-15                4848              176.25               79.1

================================================================================
DATASET: es_expirations
Shape: (4, 3)
Columns: ['Option Type', 'Expiration Date', 'Style']
--------------------------------------------------------------------------------

  Option Type Expiration Date     Style
0      Weekly      2025-01-17  European
1      Weekly      2025-01-24  European
2     Monthly      2025-02-21  American
3   Quarterly      2025-03-21  European

================================================================================
DATASET: es_vol_observations
Shape: (4, 3)
Columns: ['Tenor', 'ATM IV', '20-Day HV']
--------------------------------------------------------------------------------

     Tenor  ATM IV  20-Day HV
0   1-Week   0.189      0.152
1  1-Month   0.198      0.164
2  3-Month   0.206      0.171
3  6-Month   0.214      0.178

================================================================================
DATASET: spx_options_chain
Shape: (4, 5)
Columns: ['Expiry', 'Strike', 'Call Price', 'Put Price', 'Implied Vol']
--------------------------------------------------------------------------------

       Expiry  Strike  Call Price  Put Price  Implied Vol
0  2025-03-15    4700       310.5       42.6        0.187
1  2025-03-15    4800       230.2       70.8        0.192
2  2025-03-15    4900       160.9      112.4        0.198
3  2025-03-15    5000        95.3      170.1        0.205

================================================================================
DATASET: xsp_options_chain
Shape: (2, 5)
Columns: ['Expiry', 'Strike', 'Call Price', 'Put Price', 'Multiplier']
--------------------------------------------------------------------------------

       Expiry  Strike  Call Price  Put Price  Multiplier
0  2025-03-15     480        23.1        7.1         100
1  2025-03-15     490        16.2       11.3         100

================================================================================
DATASET: spx_specs
Shape: (6, 2)
Columns: ['Parameter', 'Value']
--------------------------------------------------------------------------------

             Parameter                Value
0           Underlying        S&P 500 Index
1  Contract Multiplier                  100
2       Exercise Style             European
3           Settlement                 Cash
4           Expiration  AM / PM (by series)
5             Exchange                 CBOE